batch_size: 16
epoch: 500
learning_rate: 1e-4
gpu: 0
num_point: 2048
optimizer: Adam
weight_decay: 1e-4
normal: False

# 默认配置
defaults:
  - model: Self
  - _self_

hydra:
  run:
    dir: log/cls/${model.name}
  job:
    chdir: True

  sweep:
    dir: log/cls
    subdir: ${model.name}